### Login (captura o token)
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "steve4@test.com",
  "password": "1aA4@56"
}

# > {%  
#     const resp = JSON.parse(response.body);
#     client.global.set("token", resp.token);
# %}
