### List all users
GET {{baseURL}}/users
Authorization: Bearer {{token}}

### Read user by id
GET {{baseURL}}/users/3
Authorization: Bearer {{token}}

### Create new user
POST {{baseURL}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Steve2",
  "email": "steve2@test.com",
  "password": "1aA3@56"
}

### Update user
PUT {{baseURL}}/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Steve",
  "email": "stave@test.com",
  "password": "1aA3@56"
}

### Partial user update
PATCH {{baseURL}}/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Steve"
}

### Delete user by id
DELETE {{baseURL}}/users/3
Authorization: Bearer {{token}}